// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNrY0v3zutSTfoVucp6uucsSNg7nGqqq4',
    appId: '1:979310389337:web:329a0cd7b6d68cc0892948',
    messagingSenderId: '979310389337',
    projectId: 'fir-sample-447be',
    authDomain: 'fir-sample-447be.firebaseapp.com',
    storageBucket: 'fir-sample-447be.appspot.com',
    measurementId: 'G-LRMV7Q9BX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkBwDPXZQkYugLa8bXXnakFrverWufa9o',
    appId: '1:979310389337:android:04b180019752fdd8892948',
    messagingSenderId: '979310389337',
    projectId: 'fir-sample-447be',
    storageBucket: 'fir-sample-447be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHtpWXtGmNb-ffa9TwB1nC0kEftC-KlIA',
    appId: '1:979310389337:ios:ccb7f89bc2d8f8c4892948',
    messagingSenderId: '979310389337',
    projectId: 'fir-sample-447be',
    storageBucket: 'fir-sample-447be.appspot.com',
    iosBundleId: 'net.sukekyo.firebaseSample',
  );
}
